export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const DISPLAY_CART_PREVIEW = "DISPLAY_CART_PREVIEW";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
